workflows:
  ios-build:
    name: iOS Build Workflow
    environment:
      xcode: latest
      vars:
        APPLE_ID: "Larrymaze88@gmail.com"
        APPLE_PASSWORD: "Shipper8811988!!!"
    scripts:
      - name: Check and List Available Schemes
        script: |
          xcodebuild -list -project ShakeFlashlight.xcodeproj
          if ! xcodebuild -list -project ShakeFlashlight.xcodeproj | grep -q "ShakeFlashlight"; then
            echo "Scheme 'ShakeFlashlight' not found. Please ensure the scheme exists and is shared."
            exit 1
          fi
      - name: Build the iOS app
        script: |
          xcodebuild -project ShakeFlashlight.xcodeproj \
          -scheme ShakeFlashlight \
          -sdk iphoneos \
          -configuration Release \
          clean build
      - name: Export the IPA
        script: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath build/ios/ShakeFlashlight.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*
