workflows:
  ios-build:
    name: iOS Build Workflow
    environment:
      xcode: latest
      vars:
        APPLE_ID: "$APPLE_ID"
        APPLE_PASSWORD: "$APPLE_PASSWORD"
    scripts:
      - name: Build the iOS app
        script: |
          xcodebuild -project ShakeFlashlight.xcodeproj \
          -scheme ShakeFlashlight \
          -sdk iphoneos \
          -configuration Release \
          clean build
      - name: Export the IPA
        script: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
          -archivePath build/ios/ShakeFlashlight.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*
